/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.node;

import java.util.*;
import minijava.analysis.*;

@SuppressWarnings("nls")
public final class AProgram extends PProgram
{
    private final LinkedList<PClassDecl> _classDecl_ = new LinkedList<PClassDecl>();

    public AProgram()
    {
        // Constructor
    }

    public AProgram(
        @SuppressWarnings("hiding") List<?> _classDecl_)
    {
        // Constructor
        setClassDecl(_classDecl_);

    }

    @Override
    public Object clone()
    {
        return new AProgram(
            cloneList(this._classDecl_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProgram(this);
    }

    public LinkedList<PClassDecl> getClassDecl()
    {
        return this._classDecl_;
    }

    public void setClassDecl(List<?> list)
    {
        for(PClassDecl e : this._classDecl_)
        {
            e.parent(null);
        }
        this._classDecl_.clear();

        for(Object obj_e : list)
        {
            PClassDecl e = (PClassDecl) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._classDecl_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._classDecl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._classDecl_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PClassDecl> i = this._classDecl_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PClassDecl) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
